#!/usr/bin/env node
// Mirror this package into the Figma "Assets" file (figma.json has the key).
// The repo is the source; Figma is the second door onto the same marks, colours and type.
//
//   node tools/figma-sync.mjs build    write the Plugin API scripts to .figma-sync/ (one per use_figma call)
//   node tools/figma-sync.mjs record   after every script ran clean: store the synced hashes in figma.json
//   node tools/figma-sync.mjs check    exit 1 if tokens, typography or any mark changed since the last sync
//
//   node tools/figma-sync.mjs upload <submitUrl>...   POST every mark SVG to upload_assets' URLs, write 05-marks.js
//
// Figma's Variables REST API is Enterprise-only, so the scripts are pushed through the Figma MCP
// (use_figma), one file per call, in name order; the marks go in through upload_assets (the plugin
// sandbox has no fetch). Every script is idempotent: variables are upserted by name, and each page,
// product frame and mark card is replaced by name, so a re-run never duplicates.
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = p => readFileSync(join(root, p), 'utf8');
const out = join(root, '.figma-sync');
const figma = JSON.parse(read('figma.json'));
const pkg = JSON.parse(read('package.json'));
const manifest = JSON.parse(read('manifest.json'));

/** Every file whose content the Figma file mirrors, with its sha256 (first 16 hex). */
function sources() {
  const files = ['css/tokens.css', 'manifest.json', ...manifest.marks.map(m => m.file)];
  return Object.fromEntries(files.map(f => [f, createHash('sha256').update(readFileSync(join(root, f))).digest('hex').slice(0, 16)]));
}

/** tokens.css -> [{group, name, css, type, value | alias, description}]. :root is "core", each [data-brand] its product. */
function tokens() {
  const css = read('css/tokens.css');
  const list = [];
  for (const block of css.matchAll(/(:root\s*|\[data-brand="([^"]+)"\][^{]*)\{([^}]*)\}/g)) {
    const group = block[2] ?? 'core';
    for (const line of block[3].split('\n')) {
      const m = line.match(/^\s*--([\w-]+):\s*([^;]+);\s*(?:\/\*\s*(.*?)\s*\*\/)?/);
      if (!m) continue;
      const [, name, raw, description = ''] = m;
      const v = raw.trim();
      const t = { group, name, css: `--${name}`, description };
      if (/^#[0-9a-f]{6}$/i.test(v)) Object.assign(t, { type: 'COLOR', value: v });
      else if (/^var\(--[\w-]+\)$/.test(v)) Object.assign(t, { type: 'ALIAS', alias: v.slice(6, -1) });
      else if (/^\d+px$/.test(v)) Object.assign(t, { type: 'FLOAT', value: parseFloat(v) });
      else if (name.startsWith('font-')) Object.assign(t, { type: 'STRING', value: v.match(/'([^']+)'/)[1] });
      else continue; // easing curves and the like have no Figma variable type
      list.push(t);
    }
  }
  return list;
}

const header = `// generated by tools/figma-sync.mjs from @boxofrules/assets ${pkg.version}; do not edit\n`;

/** Shared helpers every page script starts with. */
const lib = `
const hex = h => ({ r: parseInt(h.slice(1,3),16)/255, g: parseInt(h.slice(3,5),16)/255, b: parseInt(h.slice(5,7),16)/255 });
const solid = h => [{ type: 'SOLID', color: hex(h) }];
async function page(name) {
  let p = figma.root.children.find(x => x.name === name);
  if (!p) p = figma.root.children.find(x => x.name === 'Page 1' && !x.children.length); // Figma's empty default page
  if (!p) p = figma.createPage();
  p.name = name;
  await figma.setCurrentPageAsync(p);
  return p;
}
await figma.loadFontAsync({ family: 'Oswald', style: 'SemiBold' });
await figma.loadFontAsync({ family: 'Barlow', style: 'Regular' });
await figma.loadFontAsync({ family: 'Barlow', style: 'Medium' });
function text(chars, { size = 14, font = ['Barlow', 'Regular'], colour = '#0B0B0C', width, upper } = {}) {
  const t = figma.createText();
  t.fontName = { family: font[0], style: font[1] };
  t.characters = chars; t.fontSize = size; t.fills = solid(colour);
  if (upper) t.textCase = 'UPPER';
  if (width) { t.resize(width, t.height); t.textAutoResize = 'HEIGHT'; }
  return t;
}
/** Remove a page's top-level node by name, returning its position so the replacement lands in the same place. */
function takePlace(p, name, fallbackY) {
  const old = p.children.find(n => n.name === name);
  if (!old) return { x: 0, y: fallbackY() };
  const at = { x: old.x, y: old.y }; old.remove(); return at;
}
const bottom = p => () => p.children.reduce((y, n) => Math.max(y, n.y + n.height + 160), 0);
`;

function readmeScript(sha, date) {
  const lines = [
    ['Box Of Rules assets', 'title'],
    [`A mirror of @boxofrules/assets ${pkg.version}, synced ${date} from ${sha}.`, 'lead'],
    ['The repo is the source: github.com/boxofrules/assets, served at cdn.boxofrules.com. This file is rebuilt from it by tools/figma-sync.mjs, so anything changed here is a proposal. Export it and land it in the repo by pull request, or the next sync will overwrite it.', 'body'],
    ['Colours: every token in css/tokens.css is a variable in the Box Of Rules collection, with its CSS name as the code syntax. Blue leads every public Box Of Rules visual; amber is the accent and the plugins CTA.', 'body'],
    ['Typography: Oswald headings, Barlow body, on every site. Plugins takes Unbounded for headings; Synth.Directory stays on Barlow throughout.', 'body'],
    ['Marks: every mark in manifest.json, one frame per product, named by its path in the repo, with where it goes and where it never goes. Never redraw, crop or recolour a mark. If a surface is not listed, ask James.', 'body'],
  ];
  return header + lib + `
const p = await page('Read me');
const at = takePlace(p, 'Read me', () => 0);
const f = figma.createAutoLayout('VERTICAL', { name: 'Read me', itemSpacing: 20, paddingTop: 64, paddingBottom: 64, paddingLeft: 64, paddingRight: 64 });
f.fills = solid('#0B0B0C'); f.x = at.x; f.y = at.y;
for (const [chars, kind] of ${JSON.stringify(lines)}) {
  const t = kind === 'title' ? text(chars, { size: 64, font: ['Oswald', 'SemiBold'], colour: '#69AFBF', upper: true })
    : text(chars, { size: kind === 'lead' ? 22 : 17, font: ['Barlow', kind === 'lead' ? 'Medium' : 'Regular'], colour: kind === 'lead' ? '#ECE6D8' : '#B7B0A0', width: 760 });
  f.appendChild(t);
}
return { page: p.id, frame: f.id };
`;
}

function variablesScript(list) {
  return header + `
const hex = h => ({ r: parseInt(h.slice(1,3),16)/255, g: parseInt(h.slice(3,5),16)/255, b: parseInt(h.slice(5,7),16)/255, a: 1 });
const tokens = ${JSON.stringify(list)};
const NAME = 'Box Of Rules';
let col = (await figma.variables.getLocalVariableCollectionsAsync()).find(c => c.name === NAME);
if (!col) { col = figma.variables.createVariableCollection(NAME); col.renameMode(col.modes[0].modeId, 'Value'); }
const mode = col.modes[0].modeId;
const existing = await figma.variables.getLocalVariablesAsync();
const byName = new Map(existing.filter(v => v.variableCollectionId === col.id).map(v => [v.name, v]));
const figType = t => t.type === 'ALIAS' ? (tokens.find(x => x.name === t.alias && x.group === 'core') ?? tokens.find(x => x.name === t.alias)).type : t.type;
const scopes = t => t.type === 'STRING' ? ['FONT_FAMILY'] : t.type === 'FLOAT' ? ['WIDTH_HEIGHT'] : ['ALL_FILLS', 'STROKE_COLOR', 'EFFECT_COLOR'];
const made = [], updated = [];
const vars = {};
for (const t of tokens) {
  const name = t.group + '/' + t.name;
  let v = byName.get(name);
  const type = figType(t);
  if (v && v.resolvedType !== type) { v.remove(); v = null; }
  if (!v) { v = figma.variables.createVariable(name, col, type); made.push(name); } else updated.push(name);
  v.description = t.description;
  v.scopes = scopes({ type });
  v.setVariableCodeSyntax('WEB', 'var(' + t.css + ')');
  vars[t.group + ':' + t.name] = v;
  byName.delete(name);
}
for (const t of tokens) {
  const v = vars[t.group + ':' + t.name];
  if (t.type === 'ALIAS') {
    const target = vars['core:' + t.alias] ?? vars[t.group + ':' + t.alias];
    v.setValueForMode(mode, { type: 'VARIABLE_ALIAS', id: target.id });
  } else v.setValueForMode(mode, t.type === 'COLOR' ? hex(t.value) : t.value);
}
const removed = [...byName.keys()];
for (const v of byName.values()) v.remove(); // tokens gone from tokens.css leave Figma too
return { collection: col.id, made, updated: updated.length, removed };
`;
}

function coloursScript(list) {
  const colours = list.filter(t => t.type === 'COLOR' || (t.type === 'ALIAS' && list.find(x => x.name === t.alias && x.type === 'COLOR')));
  const resolve = t => t.type === 'ALIAS' ? list.find(x => x.name === t.alias && x.group === 'core').value : t.value;
  const groups = [...new Set(colours.map(t => t.group))].map(g => ({ group: g, items: colours.filter(t => t.group === g).map(t => ({ ...t, hex: resolve(t) })) }));
  return header + lib + `
const groups = ${JSON.stringify(groups)};
const col = (await figma.variables.getLocalVariableCollectionsAsync()).find(c => c.name === 'Box Of Rules');
const vars = new Map((await figma.variables.getLocalVariablesAsync()).filter(v => v.variableCollectionId === col.id).map(v => [v.name, v]));
const p = await page('Colours');
const at = takePlace(p, 'Colours', () => 0);
const f = figma.createAutoLayout('VERTICAL', { name: 'Colours', itemSpacing: 48, paddingTop: 64, paddingBottom: 64, paddingLeft: 64, paddingRight: 64 });
f.fills = solid('#FFFFFF'); // white, so bone and the inks all read without an outline f.x = at.x; f.y = at.y;
f.appendChild(text('Colours', { size: 48, font: ['Oswald', 'SemiBold'], upper: true }));
f.appendChild(text('Every swatch is bound to its variable in the Box Of Rules collection. Source: css/tokens.css.', { size: 16, colour: '#131210', width: 900 }));
for (const g of groups) {
  const sec = figma.createAutoLayout('VERTICAL', { name: g.group, itemSpacing: 16 }); sec.fills = [];
  f.appendChild(sec);
  sec.appendChild(text(g.group === 'core' ? 'Box Of Rules' : g.group, { size: 24, font: ['Oswald', 'SemiBold'], upper: true }));
  const row = figma.createAutoLayout('HORIZONTAL', { name: 'swatches', itemSpacing: 16, counterAxisSpacing: 24, layoutWrap: 'WRAP' });
  row.fills = []; sec.appendChild(row); row.resize(1400, row.height); row.primaryAxisSizingMode = 'FIXED';
  for (const t of g.items) {
    const card = figma.createAutoLayout('VERTICAL', { name: t.group + '/' + t.name, itemSpacing: 6 }); card.fills = [];
    const chip = figma.createRectangle(); chip.resize(200, 120); chip.cornerRadius = 8; chip.name = 'swatch';
    const v = vars.get(t.group + '/' + t.name);
    chip.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: hex(t.hex) }, 'color', v)];
    card.appendChild(chip);
    card.appendChild(text(t.name + (t.alias ? ' = ' + t.alias : ''), { size: 16, font: ['Barlow', 'Medium'] }));
    card.appendChild(text(t.hex.toUpperCase() + '   ' + t.css, { size: 13, colour: '#131210' }));
    if (t.description) card.appendChild(text(t.description, { size: 12, colour: '#948D82', width: 200 }));
    row.appendChild(card);
  }
}
return { page: p.id, frame: f.id, groups: groups.length, swatches: groups.reduce((n, g) => n + g.items.length, 0) };
`;
}

function typographyScript() {
  const typo = manifest.typography;
  const sites = Object.entries(typo).filter(([k]) => !k.startsWith('$') && k !== 'desktop-plugins').map(([k, v]) => [k, v.heading, v.body, v.wordmark]);
  const plugins = Object.entries(typo['desktop-plugins'] ?? {}).filter(([k]) => !k.startsWith('$')).map(([k, v]) => [k, v.heading, v.body, v.note ?? (v.never ? 'Never: ' + v.never : '')]);
  return header + lib + `
await figma.loadFontAsync({ family: 'Unbounded', style: 'Bold' });
const p = await page('Typography');
const at = takePlace(p, 'Typography', () => 0);
const f = figma.createAutoLayout('VERTICAL', { name: 'Typography', itemSpacing: 40, paddingTop: 64, paddingBottom: 64, paddingLeft: 64, paddingRight: 64 });
f.fills = solid('#ECE6D8'); f.x = at.x; f.y = at.y;
f.appendChild(text('Typography', { size: 48, font: ['Oswald', 'SemiBold'], upper: true }));
f.appendChild(text('The faces in fonts/ (OFL). Headings Oswald, body Barlow, everywhere, unless the product says otherwise below. Source: manifest.json typography; the families are also variables (core/font-heading, core/font-body, plugins/font-heading).', { size: 16, colour: '#131210', width: 1000 }));
const specimens = [
  ['Oswald, headings', ['Oswald', 'SemiBold'], 'Box Of Rules. Digitally analogue.', true],
  ['Barlow, body', ['Barlow', 'Regular'], 'Plugins, instruments and tools for people who make music. Barlow at 400, 500, 600 and 700.', false],
  ['Unbounded 700, plugins.boxofrules.com headings only', ['Unbounded', 'Bold'], 'Plugins', true],
];
for (const [label, font, sample, upper] of specimens) {
  const s = figma.createAutoLayout('VERTICAL', { name: label, itemSpacing: 8 }); s.fills = [];
  f.appendChild(s);
  s.appendChild(text(label, { size: 14, font: ['Barlow', 'Medium'], colour: '#948D82' }));
  s.appendChild(text(sample, { size: upper ? 56 : 24, font, upper, width: 1000 }));
}
const table = (title, rows) => {
  const s = figma.createAutoLayout('VERTICAL', { name: title, itemSpacing: 10 }); s.fills = [];
  f.appendChild(s);
  s.appendChild(text(title, { size: 24, font: ['Oswald', 'SemiBold'], upper: true }));
  for (const r of rows) {
    const row = figma.createAutoLayout('HORIZONTAL', { name: r[0], itemSpacing: 24 }); row.fills = [];
    s.appendChild(row);
    row.appendChild(text(r[0], { size: 15, font: ['Barlow', 'Medium'], width: 200 }));
    for (const c of r.slice(1)) row.appendChild(text(c ?? '', { size: 14, colour: '#131210', width: r.length > 2 ? 260 : 800 }));
  }
};
table('Sites: heading, body, wordmark', ${JSON.stringify(sites)});
table('Desktop plugins: heading, body, note', ${JSON.stringify(plugins)});
return { page: p.id, frame: f.id };
`;
}

/** The marks: upload_assets imports each SVG as a vector frame (placed ids in \`placed\`, path -> node id);
 *  this script moves each into its card, replacing the card of the same path, one frame per product in manifest order. */
function marksScript(placed) {
  const dark = m => /white|dark/.test(m.variant) || ['plugins', 'waveform-analyser'].includes(m.product);
  const items = manifest.marks.map(m => ({ path: m.file, product: m.product, variant: m.variant, use: m.use ?? '', never: m.never ?? '', dark: dark(m), id: placed[m.file] }));
  const products = [...new Set(items.map(i => i.product))];
  return header + lib + `
const products = ${JSON.stringify(products)};
const items = ${JSON.stringify(items)};
const p = await page('Marks');
function productFrame(product) {
  const name = 'marks/' + product;
  let f = p.children.find(x => x.name === name);
  if (f) return f;
  f = figma.createAutoLayout('VERTICAL', { name, itemSpacing: 24, paddingTop: 48, paddingBottom: 48, paddingLeft: 48, paddingRight: 48 });
  f.fills = solid('#FFFFFF');
  f.appendChild(text(product, { size: 36, font: ['Oswald', 'SemiBold'], upper: true }));
  const grid = figma.createAutoLayout('HORIZONTAL', { name: 'grid', itemSpacing: 24, counterAxisSpacing: 32, layoutWrap: 'WRAP' });
  grid.fills = []; f.appendChild(grid); grid.resize(4 * 360 + 3 * 24, grid.height); grid.primaryAxisSizingMode = 'FIXED';
  return f;
}
const made = [], missing = [];
for (const i of items) {
  const svg = await figma.getNodeByIdAsync(i.id);
  if (!svg) { missing.push(i.path); continue; }
  const grid = productFrame(i.product).children.find(x => x.name === 'grid');
  const old = grid.children.find(x => x.name === i.path);
  const index = old ? grid.children.indexOf(old) : grid.children.length;
  if (old) old.remove();
  const card = figma.createAutoLayout('VERTICAL', { name: i.path, itemSpacing: 6 }); card.fills = [];
  const tile = figma.createFrame(); tile.name = 'tile'; tile.resize(360, 220); tile.cornerRadius = 8;
  tile.fills = solid(i.dark ? '#0B0B0C' : '#ECE6D8');
  tile.appendChild(svg); svg.name = i.path.split('/').pop().replace('.svg', '');
  const s = Math.min(300 / svg.width, 160 / svg.height);
  svg.rescale(s);
  svg.x = (360 - svg.width) / 2; svg.y = (220 - svg.height) / 2;
  card.appendChild(tile);
  card.appendChild(text(i.path, { size: 14, font: ['Barlow', 'Medium'], width: 360 }));
  card.appendChild(text(i.variant, { size: 12, colour: '#131210', width: 360 }));
  if (i.use) card.appendChild(text('Use: ' + i.use, { size: 12, colour: '#131210', width: 360 }));
  if (i.never) card.appendChild(text('Never: ' + i.never, { size: 12, colour: '#C42424', width: 360 }));
  grid.insertChild(Math.min(index, grid.children.length), card);
  made.push(card.id);
}
// stack the product frames in manifest order; anything else left on the page is a stray import
let y = 0;
for (const name of products.map(x => 'marks/' + x)) {
  const f = p.children.find(x => x.name === name);
  if (f) { f.x = 0; f.y = y; y += f.height + 160; }
}
const strays = p.children.filter(n => !n.name.startsWith('marks/')).map(n => n.id + ' ' + n.name);
return { page: p.id, made: made.length, missing, strays };
`;
}

const cmd = process.argv[2];
if (cmd === 'build') {
  const sha = execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim();
  const date = new Date().toISOString().slice(0, 10);
  const list = tokens();
  rmSync(out, { recursive: true, force: true });
  mkdirSync(out);
  const scripts = [['01-variables', variablesScript(list)], ['02-read-me', readmeScript(sha, date)], ['03-colours', coloursScript(list)], ['04-typography', typographyScript()],
];
  for (const [name, code] of scripts) {
    if (code.length > 50000) throw new Error(`${name} is ${code.length} characters, over use_figma's 50,000`);
    writeFileSync(join(out, name + '.js'), code);
  }
  console.log(`${scripts.length} scripts in .figma-sync/ for ${figma.url}\n` + readdirSync(out).map(f => `  ${f}  ${readFileSync(join(out, f)).length} chars`).join('\n'));
  console.log(`then: upload_assets count=${manifest.marks.length} on the Marks page, and \`node tools/figma-sync.mjs upload <submitUrl>...\``);
} else if (cmd === 'upload') {
  // POST every mark, in manifest order, to the single-use submit URLs upload_assets handed out
  const urls = process.argv.slice(3);
  if (urls.length !== manifest.marks.length) throw new Error(`need ${manifest.marks.length} submit URLs, got ${urls.length}`);
  const placed = {};
  await Promise.all(manifest.marks.map(async (m, n) => {
    const form = new FormData();
    form.append('file', new Blob([readFileSync(join(root, m.file))], { type: 'image/svg+xml' }), m.file.split('/').pop());
    const r = await (await fetch(urls[n], { method: 'POST', body: form })).json();
    if (!r.success) throw new Error(`${m.file}: ${JSON.stringify(r)}`);
    placed[m.file] = r.placedOnNodeId;
  }));
  const code = marksScript(placed);
  writeFileSync(join(out, '05-marks.js'), code);
  console.log(`${Object.keys(placed).length} marks uploaded; push .figma-sync/05-marks.js (${code.length} chars) to lay them out`);
} else if (cmd === 'record') {
  figma.synced = { version: pkg.version, commit: execSync('git rev-parse --short HEAD', { cwd: root }).toString().trim(), date: new Date().toISOString().slice(0, 10), sources: sources() };
  writeFileSync(join(root, 'figma.json'), JSON.stringify(figma, null, 2) + '\n');
  console.log(`figma.json: ${Object.keys(figma.synced.sources).length} sources recorded at ${figma.synced.commit}`);
} else if (cmd === 'check') {
  const now = sources(), was = figma.synced?.sources ?? {};
  const drift = [...new Set([...Object.keys(now), ...Object.keys(was)])].filter(f => now[f] !== was[f]);
  if (!drift.length) { console.log(`Figma is in sync with ${figma.synced.version} (${figma.synced.commit}, ${figma.synced.date})`); process.exit(0); }
  console.log(`Figma is behind the repo on ${drift.length} file(s); run build, push each .figma-sync/ script through use_figma, then record:\n` + drift.map(f => '  ' + f).join('\n'));
  process.exit(1);
} else {
  console.log('usage: node tools/figma-sync.mjs build | record | check');
  process.exit(2);
}
